### ISSUE TITLE
Strings are outdated

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#1001]
I think this is a  consequence to our upgrade of the mozfr server last week to a newer Debian, it seems that strings are no longer correctly extracted, here is the log of the extraction which shows Python errors:

`tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Request summary:
* Create data snapshot: true
* Force TMX creation: false
* Update repositories: true
* Elaborate all locales: true
Checking if Transvision sources are available...
Activating virtualenv...
pulling from https://hg.mozilla.org/l10n/gecko-strings/
no changes found
Create cache for gecko_strings/en-US
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
There are no changes to pull for gecko_strings/ach
There are no changes to pull for gecko_strings/af
There are no changes to pull for gecko_strings/an
There are no changes to pull for gecko_strings/ar
There are no changes to pull for gecko_strings/ast
There are no changes to pull for gecko_strings/az
There are no changes to pull for gecko_strings/be
There are no changes to pull for gecko_strings/bg
There are no changes to pull for gecko_strings/bn
There are no changes to pull for gecko_strings/bo
There are no changes to pull for gecko_strings/br
There are no changes to pull for gecko_strings/brx
There are no changes to pull for gecko_strings/bs
There are no changes to pull for gecko_strings/ca
There are no changes to pull for gecko_strings/ca-valencia
There are no changes to pull for gecko_strings/cak
There are no changes to pull for gecko_strings/ckb
There are no changes to pull for gecko_strings/cs
Updating gecko_strings/cy
pulling from incoming.hg
searching for changes
adding changesets
adding manifests
adding file changes
added 1 changesets with 1 changes to 1 files
new changesets 1ca78f41e4b1 (1 drafts)
1 files updated, 0 files merged, 0 files removed, 0 files unresolved
Create cache for gecko_strings/cy
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
There are no changes to pull for gecko_strings/da
There are no changes to pull for gecko_strings/de
There are no changes to pull for gecko_strings/dsb
Updating gecko_strings/el
pulling from incoming.hg
searching for changes
adding changesets
adding manifests
adding file changes
added 1 changesets with 1 changes to 1 files
new changesets 58bb6f61c465 (1 drafts)
1 files updated, 0 files merged, 0 files removed, 0 files unresolved
Create cache for gecko_strings/el
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
There are no changes to pull for gecko_strings/en-CA
There are no changes to pull for gecko_strings/en-GB
There are no changes to pull for gecko_strings/eo
There are no changes to pull for gecko_strings/es-AR
There are no changes to pull for gecko_strings/es-CL
There are no changes to pull for gecko_strings/es-ES
There are no changes to pull for gecko_strings/es-MX
There are no changes to pull for gecko_strings/et
There are no changes to pull for gecko_strings/eu
There are no changes to pull for gecko_strings/fa
There are no changes to pull for gecko_strings/ff
There are no changes to pull for gecko_strings/fi
There are no changes to pull for gecko_strings/fr
There are no changes to pull for gecko_strings/fy-NL
There are no changes to pull for gecko_strings/ga-IE
There are no changes to pull for gecko_strings/gd
There are no changes to pull for gecko_strings/gl
There are no changes to pull for gecko_strings/gn
There are no changes to pull for gecko_strings/gu-IN
There are no changes to pull for gecko_strings/he
There are no changes to pull for gecko_strings/hi-IN
There are no changes to pull for gecko_strings/hr
There are no changes to pull for gecko_strings/hsb
There are no changes to pull for gecko_strings/hu
There are no changes to pull for gecko_strings/hy-AM
Updating gecko_strings/hye
pulling from incoming.hg
searching for changes
adding changesets
adding manifests
adding file changes
added 1 changesets with 2 changes to 2 files
new changesets bda6002b7be4 (1 drafts)
2 files updated, 0 files merged, 0 files removed, 0 files unresolved
Create cache for gecko_strings/hye
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
There are no changes to pull for gecko_strings/ia
There are no changes to pull for gecko_strings/id
There are no changes to pull for gecko_strings/is
There are no changes to pull for gecko_strings/it
There are no changes to pull for gecko_strings/ja
There are no changes to pull for gecko_strings/ja-JP-mac
There are no changes to pull for gecko_strings/ka
There are no changes to pull for gecko_strings/kab
There are no changes to pull for gecko_strings/kk
There are no changes to pull for gecko_strings/km
There are no changes to pull for gecko_strings/kn
There are no changes to pull for gecko_strings/ko
There are no changes to pull for gecko_strings/lij
There are no changes to pull for gecko_strings/lo
There are no changes to pull for gecko_strings/lt
There are no changes to pull for gecko_strings/ltg
There are no changes to pull for gecko_strings/lv
There are no changes to pull for gecko_strings/meh
There are no changes to pull for gecko_strings/mix
There are no changes to pull for gecko_strings/mk
There are no changes to pull for gecko_strings/ml
There are no changes to pull for gecko_strings/mr
There are no changes to pull for gecko_strings/ms
There are no changes to pull for gecko_strings/my
There are no changes to pull for gecko_strings/nb-NO
There are no changes to pull for gecko_strings/ne-NP
There are no changes to pull for gecko_strings/nl
There are no changes to pull for gecko_strings/nn-NO
There are no changes to pull for gecko_strings/oc
There are no changes to pull for gecko_strings/pa-IN
There are no changes to pull for gecko_strings/pl
Updating gecko_strings/pt-BR
pulling from incoming.hg
searching for changes
adding changesets
adding manifests
adding file changes
added 4 changesets with 5 changes to 5 files
new changesets 22dc3c23f1fe:1c015619e0d0 (4 drafts)
5 files updated, 0 files merged, 0 files removed, 0 files unresolved
Create cache for gecko_strings/pt-BR
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_products.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
There are no changes to pull for gecko_strings/pt-PT
There are no changes to pull for gecko_strings/rm
There are no changes to pull for gecko_strings/ro
There are no changes to pull for gecko_strings/ru
There are no changes to pull for gecko_strings/scn
There are no changes to pull for gecko_strings/si
There are no changes to pull for gecko_strings/sk
There are no changes to pull for gecko_strings/sl
There are no changes to pull for gecko_strings/son
There are no changes to pull for gecko_strings/sq
There are no changes to pull for gecko_strings/sr
There are no changes to pull for gecko_strings/sv-SE
There are no changes to pull for gecko_strings/szl
There are no changes to pull for gecko_strings/ta
There are no changes to pull for gecko_strings/te
There are no changes to pull for gecko_strings/th
There are no changes to pull for gecko_strings/tl
There are no changes to pull for gecko_strings/tr
There are no changes to pull for gecko_strings/trs
There are no changes to pull for gecko_strings/uk
There are no changes to pull for gecko_strings/ur
There are no changes to pull for gecko_strings/uz
There are no changes to pull for gecko_strings/vi
There are no changes to pull for gecko_strings/wo
There are no changes to pull for gecko_strings/xh
There are no changes to pull for gecko_strings/zam
There are no changes to pull for gecko_strings/zh-CN
There are no changes to pull for gecko_strings/zh-TW
Update GitHub repository
From https://github.com/mozilla-l10n/www-l10n
   5d0f7b3ae..b6619b115  master     -> origin/master
Updating 5d0f7b3ae..b6619b115
Fast-forward
 el/mozorg/about/legal.ftl | 10 ++++++++++
 1 file changed, 10 insertions(+)
Extract strings for mozilla.org (Fluent)
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_projectconfig.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Update GitHub repository
Already up to date.
Extract strings for Firefox for iOS
Extraction of strings from XLIFF file
af: 795 strings
an: 795 strings
anp: 795 strings
ar: 795 strings
ast: 795 strings
az: 795 strings
bg: 795 strings
bn: 795 strings
bo: 795 strings
br: 795 strings
bs: 795 strings
ca: 795 strings
co: 795 strings
cs: 795 strings
cy: 795 strings
da: 795 strings
de: 795 strings
dsb: 795 strings
el: 795 strings
en-CA: 795 strings
en-GB: 795 strings
en-US: 795 strings
eo: 795 strings
es: 795 strings
es-AR: 795 strings
es-CL: 795 strings
es-MX: 795 strings
eu: 795 strings
fa: 795 strings
fi: 795 strings
fr: 795 strings
ga-IE: 795 strings
gd: 795 strings
gl: 795 strings
gu-IN: 795 strings
he: 795 strings
hi-IN: 795 strings
hr: 795 strings
hsb: 795 strings
hu: 795 strings
hy-AM: 795 strings
ia: 795 strings
id: 795 strings
is: 795 strings
it: 795 strings
ja: 795 strings
jv: 795 strings
ka: 795 strings
kab: 795 strings
kk: 795 strings
km: 795 strings
kn: 795 strings
ko: 795 strings
lo: 795 strings
lt: 795 strings
lv: 795 strings
ml: 795 strings
mr: 795 strings
ms: 795 strings
my: 795 strings
nb-NO: 795 strings
ne-NP: 795 strings
nl: 795 strings
nn-NO: 795 strings
oc: 795 strings
or: 795 strings
pa-IN: 795 strings
pl: 795 strings
pt-BR: 795 strings
pt-PT: 795 strings
rm: 795 strings
ro: 795 strings
ru: 795 strings
sat: 795 strings
ses: 795 strings
si: 795 strings
sk: 795 strings
sl: 795 strings
sq: 795 strings
su: 795 strings
sv-SE: 795 strings
ta: 795 strings
te: 795 strings
th: 795 strings
tl: 795 strings
tr: 795 strings
uk: 795 strings
ur: 795 strings
uz: 795 strings
vi: 795 strings
zgh: 795 strings
zh-CN: 795 strings
zh-TW: 795 strings
Update GitHub repository
Already up to date.
Extract strings for android-l10n
Traceback (most recent call last):
  File "/home/pascalc/transvision//app/scripts/tmx/tmx_projectconfig.py", line 3, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Creating extraction timestamp for cache system
Deleting all the old cached files
Deleting custom TMX files
Creating a snapshot of extracted strings in web/data.tar.gz
Snapshot created in the web root for download
`

**Comment by flodolo** [comment]
I think the problem is the virtualenv. I removed it and re-run setup.sh, not it's running glossaire.sh (a bit slow).

I'll close when it's complete.

**Comment by flodolo** [comment]
It should be working now, let me know if you see anything weird.

**Comment by pascalchevrel** [comment]
It works now, thanks.
