### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#194]
We need to document the release process on the Wiki to make sure nothing is forgotten. I am going to take that one since I am the release manager.

**Comment by pascalchevrel** [comment]
Also don't forget to generate new documentation:
```bash
php ./phpDocumentor.phar -d "./app/classes/Transvision/" -t "web/docs/" --template="responsive-twig" --title="Transvision classes documentation"
```

**Comment by TheoChevalier** [comment]
I guess this is good enough to close this issue: https://github.com/mozfr/transvision/wiki/Release-Process
Removed the documentation part since it’s now generated by the webhook of transvision-beta
