### ISSUE TITLE
new view: 4 spanishes

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#22]
Add a view for all 4 Spanishes to compare strings, maybe part of a multiview/multilocales search

**Comment by flodolo** [comment]
@TheoChevalier 
Thoughts? I think we should close this one.

**Comment by enderandpeter** [comment]
Nowadays, the "3 locales search" feature lets you compare 3 Spanishes at least...

**Comment by flodolo** [comment]
Yes, and the ask here was to have 4. I'm going to close this, as I don't think it's useful.

On the other hand, there's an open issue to either clean up or remove the 3 locales view.
https://github.com/mozfr/transvision/issues/835
