### ISSUE TITLE
[enhancement] have a specific friendly-looking logo/icon/favicon

### ISSUE THREAD

**Issue by goofy-bz** [mozfr/transvision#223]
this is a minor request. There seems to be no logo any longer since https://github.com/mozfr/transvision/commit/725d9787d004491fd100273dedae25f50d2b9373#diff-581b5e9ce03a747504f4a3e8d5e14ffd

Would you please consider having a new one?
Maybe it should be done by a call to graphic arts contribution on Mozilla l10n groups  (so it may arise extra interest for Transvision)

**Comment by flodolo** [comment]
What about using the new [Community Design](https://github.com/mozilla/Community-Design/) group? They seem to be doing a pretty good job

**Comment by flodolo** [comment]
Side thought: should it be only a favicon or also a full logo to use somewhere in the page? I'd like the idea of having both.

**Comment by pascalchevrel** [comment]
Ideally a logo that could be declined as a favicon, I would also like something that can be printed on a Tshirt.

**Comment by pascalchevrel** [comment]
I didn't know about the Community Design group, apparently they set up their GitHub repo while I was on medical leave :) I just filed an issue there https://github.com/mozilla/Community-Design/issues/34

**Comment by pascalchevrel** [comment]
Elio Qoshi created a great set of logos and all the graphics are there:
https://github.com/mozilla/Community-Design/tree/master/Transvision

Taking this bug for the implementation
