### ISSUE TITLE
add gettext files to transvision

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#27]
We could add all the gettext files, although I am not sure how to present more than a couple of projects in addition to repos, there is also the risk of polluting with noise the main use of Transvision which is to look for strings in repos.Silme supports gettext extraction, maybe treat all gettext project as a single repo and call it "web sites"

**Comment by MikkCZ** [comment]
I am interested in getting deeper into this and try to mockup some solution for displaying the gettext extracted strings in current layout or a similar one.

I see two problems:
- adding too many projects (Repositories) can make navigation between them messy
- gettext is more like .lang files and missing any entity IDs

The repository menu might desire some redesign for larger number of entries (30 if all web projects listed on webdashboard would be added). Adding a displaying them all as one "Repository" might be a workaround, but confusing when reporting bugs etc. The number of potential results for too frequent term would be also huge. Not all of the projects are available for all locales too.

As for the missing entity IDs, it might be worth considering change the way how .lang file strings are listed, as their IDs have currently no connection to their actual position in the files, or do they?

**Comment by flodolo** [comment]
We have a Gettext parser.
