### ISSUE TITLE
Write a sanity check php script

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#278]
There are a few things that can cause bugs that are not easy to detect and that mostly depend on the server configuration and config.ini, we could make additional checks in the code but also just create a sanity check script to make sure we don't have a stupid config bug in the release. 

Examples:
- cache folder should be writable
- all log files should exist
- php should be > 5.4
- TMX folder should exist and contain data
- all paths in config.ini are accessible / contain the expected data

I probably forget others, but it's mostly the result of bad settings int the configuration file and bad permissions for files/folders.

We could have this script ran after dev-setup.sh to warn of obvious errors, maybe we could also have it ran by Travis (I guess that if the script returns true/false, it should make a build fail.

That's something useful that could also be done without Mozilla knowledge, so that sounds like a nice task for a new dev.

**Comment by Mte90** [comment]
I think that is ready but a review can helpful to define what is missing.
https://github.com/mozfr/transvision/pull/857
