### ISSUE TITLE
Searches with non-ASCII characters like umlauts or accented characters are always case-sensitive

### ISSUE THREAD

**Issue by Archaeopteryx** [mozfr/transvision#386]
Searches with non-ASCII characters like umlauts or accented characters are always case-sensitive, e.g.

http://transvision.mozfr.org/?recherche=%C3%BCberdeckende&repo=gaia&sourcelocale=en-US&locale=de&search_type=strings_entities returns nothing

http://transvision.mozfr.org/?recherche=%C3%9Cberdeckende&repo=gaia&sourcelocale=en-US&locale=de&search_type=strings_entities finds the strings.

**Comment by flodolo** [comment]
I'm trying to wrap my head around this. It definitely works by adding `/u` to regexps, but then `str_replace` fails to highlight the results, which probably means we're mixing up charsets.
