### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#403]
We should create a CONTRIBUTING.md file and move all contribution documentation such as code guidelines there. Github now presents this file for Pull requests and new issues ti contributors:
https://github.com/blog/1184-contributing-guidelines

**Comment by SkySymbol** [comment]
Can I work on it ?

**Comment by flodolo** [comment]
Sure, nobody is currently assigned. 

I meant to assign this to you, but apparently I can't (I don't see your name in the list of available people).

**Comment by pascalchevrel** [comment]
I sent an invite to SkySymbol to be part of the Transvision repo team, means that now he can be assgned to issues :)

**Comment by SkySymbol** [comment]
Thanks for the invitation. Currently I have 3 sections in the file :

* Getting Started (witch explains how to install Transvision)
* Code Conventions
* Contributions tips

Should we add another topics ? From my experience about getting started
with the Transvision project, I would recommend to add a link to help with
pull requests, such as @flodolo's tutorial.

**Comment by pascalchevrel** [comment]
I think it's a good start, do you have a branch we could look at online?

**Comment by SkySymbol** [comment]
There you go : https://github.com/SkySymbol/transvision/tree/contributing.md
