### ISSUE TITLE
Create a view listing translation inconsistencies

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#410]
Besnik would like a view that would list all the inconsistencies in translation that may happen when the same English string is used in several contexts but there are different translations for them. The differences in translation can be on purpose, but not always.

Ex:
English uses "Add to bookmark" in two different entities, but the locale uses two different translations, /ex in French 'Ajouter aux marque-pages' and 'Ajout aux marque-pages'.

The view should find all duplicate English strings for a repo and then check if the translations are different too. If there are different, present the data in a way that is understandable.

**Comment by flodolo** [comment]
I'm going to do some experiments on this.
