### ISSUE TITLE
Production server not updating sources

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#415]
http://transvision.mozfr.org/?sourcelocale=en-US&locale=it&repo=aurora&search_type=entities&recherche=mail/chrome/overrides/netError.dtd:cspBlocked.longDesc

String is reported as missing, but it [landed on Dec 28](http://hg.mozilla.org/releases/l10n/mozilla-aurora/it/rev/0d8001fffcea#l11.14). I assume we're still having issues with permissions :-\

**Comment by flodolo** [comment]
Same search on my local VM works as expected
![index](https://cloud.githubusercontent.com/assets/3644868/5601917/a01cd536-9327-11e4-88a0-f9a27d980e36.png)

**Comment by pascalchevrel** [comment]
checkrepo was at false in glossaire, this is fixed now
