### ISSUE TITLE
entity view is 500 because of cache

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#417]
[Wed Jan 14 17:39:25 2015] PHP Fatal error:  Class 'Transvision\Cache' not found in /home/pascalc/repos/github/transvisionpascal/app/models/api/entity.php on line 6

We need to make a use statement in that file and probably check that no other caching calls were forgotten:
```php
use Cache\Cache;
```

**Comment by flodolo** [comment]
Interesting. I though these cases would be covered by this :-\
https://github.com/mozfr/transvision/blob/master/app/inc/init.php#L5

**Comment by pascalchevrel** [comment]
I think that 'use', like 'namespace', is per file
