### ISSUE TITLE
[Suggestion] Add Number of results found in "Variables Overview" view

### ISSUE THREAD

**Issue by anefzaoui** [mozfr/transvision#438]
e.g. http://transvision.mozfr.org/variables/?locale=ar&repo=gaia
I'd like to see how many results are shown so after I fix the mistaken variables and refresh I can see the new number and know there has been a difference.
This is useful especially when the number of errors is big.

**Comment by SkySymbol** [comment]
Can I take this issue ?

**Comment by pascalchevrel** [comment]
all yours :)
