### ISSUE TITLE
Searches take 18s if cache is disabled

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#443]
I noticed that we have a performance regression when the cache is disabled (which I need for development), searches take up to 20s.

This is because the bugzilla class does an http query per search result if the cache is disabled.

**Comment by flodolo** [comment]
This should be fixed, right?

**Comment by pascalchevrel** [comment]
needs a new tag on https://github.com/mozilla-l10n/phpclass-bugzilla/  ;)

**Comment by flodolo** [comment]
Completely forgot about that, done
https://github.com/mozilla-l10n/phpclass-bugzilla/releases/tag/0.1.3
