### ISSUE TITLE
False positive in Variables Overview

### ISSUE THREAD

**Issue by petercpg** [mozfr/transvision#444]
(Refer: http://transvision.mozfr.org/variables/?locale=zh-TW&repo=central )

In Variables Overview, transvision complains about rights.webservices-term might have potential errors, however they are false positives. I guess it is caused by the word "$500"?

**Comment by flodolo** [comment]
Looking into this.

Basically $500 is a valid variable format for some files, so I think we need to create a list of strings to be ignored (like these).
