### ISSUE TITLE
Gaia Master for Danish extraction fails, leading to corrupt php cache file

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#447]
file generated:
```php
<?php
$tmx = [
```

**Comment by pascalchevrel** [comment]
Found the bug, it is not in our code, there is a "Windows1252" encoded properties file in the Gaia repository for Gaia that makes the Silme library stop the python script, so this needs to be fixed by the localizer. 

I am going to fix tmxmaker.py to print an error message we will see in the cron job message and to close the php file when it happens

**Comment by flodolo** [comment]
That's weird, it seems to work for me locally.
```
-rw-r--r--  1 flodolo flodolo 470653 Apr  8 14:04 cache_da.php
-rw-r--r--  1 flodolo flodolo 461834 Apr  8 14:04 cache_en-US.php
-rw-r--r--  1 flodolo flodolo 933547 Jun 10  2014 memoire_en-US_da.tmx
```

**Comment by pascalchevrel** [comment]
Jorgen fixed the encoding issue last night so you probably have a fresher hg checkout:
https://hg.mozilla.org/gaia-l10n/da/rev/3f8842dd4407

I had the same bug locally with hg repos  a couple days old

**Comment by flodolo** [comment]
OK, makes sense then (I did update 'da' before trying).
