### ISSUE TITLE
views/stats.php is unused, move stats json files to /cache

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#454]
```views/stats.php``` seems to be unused these days, we should either remove it or re-implement it somewhere.

Also: ```stats_requests.json``` and ```stats_locales.json``` are created inside the webroot, they should be in /cache, at least we only have one place writable by the user running Apache.

**Comment by SkySymbol** [comment]
Can I work on it? I think about making the code inside ```views/stats.php``` a function and put it in ```Utils.php```
