### ISSUE TITLE
Server not updating corrently after mozfr restore

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#459]
Compare
https://transvision.mozfr.org/string/?entity=toolkit/chrome/global/aboutServiceWorkers.properties:b2gtitle&repo=central

With
http://transvision.flod.org/?recherche=b2gtitle&repo=central&sourcelocale=en-US&locale=it&search_type=entities

The footer says it's updated, but it's not. I assume something is wrong with permissions or the cronjob.

**Comment by pascalchevrel** [comment]
should be fixed, next cron job is at 10AM, please close this bug if the data is not updated at 11AM

**Comment by flodolo** [comment]
Looks fixed, thanks :-)
