### ISSUE TITLE
TMX download is broken on production

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#469]
Looks like we can't download TMX from production.

[KO] https://transvision.mozfr.org/downloads/?locale=fr&tmx_format=normal&gaia=gaia
[OK] https://transvision-beta.mozfr.org/downloads/?locale=fr&tmx_format=normal&gaia=gaia

The app crashes, so I hope we have relevant info in the logs

**Comment by TheoChevalier** [comment]
Wrong permissions on web/TMX due to the issue we had on the server or missing symbolic link?

**Comment by flodolo** [comment]
Nice, had the same error on my backup server
http://transvision.flod.org/downloads/?locale=it&tmx_format=normal&gaia_1_3=gaia_1_3

The issue is that `web/download`is not writable.

**Comment by pascalchevrel** [comment]
fixed
