### ISSUE TITLE
Bust  cached javascript ressources with each new release

### ISSUE THREAD

**Issue by Archaeopteryx** [mozfr/transvision#486]
Enabling the checkbox to set the value of 'Search In' as default doesn't get used as default value the next time transvision gets loaded. Test with Firefox 38.0.5

**Comment by flodolo** [comment]
It's a cache issue (goes away with a forced reload). Not sure if we want to be less aggressive with cache
https://github.com/mozfr/transvision/blob/master/web/.htaccess#L15-L22

**Comment by pascalchevrel** [comment]
We can add a query parameter with the version number, this way the http cache will be busted with each release. Looking at the code, that's what we are already doing with css, reopening and assigning to myself.

**Comment by pascalchevrel** [comment]
fixed
