### ISSUE TITLE
← and → Flags are displayed with some queries

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#488]
Just noticed with this query https://transvision.mozfr.org/?recherche=Afin+d%27assurer+ce+service&repo=central&sourcelocale=en-US&locale=fr&search_type=strings

I guess it happens when there are two or more set of tags around the same characters.

Will comment if I see a different behavior with other queries.

**Comment by SkySymbol** [comment]
If that helps, https://transvision.mozfr.org/?recherche=ce+service&repo=aurora&sourcelocale=en-US&locale=fr&search_type=strings produces the bug, https://transvision.mozfr.org/?recherche=service&repo=aurora&sourcelocale=en-US&locale=fr&search_type=strings not. Really strange

**Comment by flodolo** [comment]
Regressions from [this](https://github.com/mozfr/transvision/commit/871329d64831f3ac50fe76d97b95898293bb2b1d#diff-b0b1fc25c8c4112ba0c48327402aa042).

Not exactly sure why a string would be marked twice though.

**Comment by flodolo** [comment]
OK, I get it know: 
```
service
←service→ (because of “service”)
←servi←ce→→ (because of “ce”)
```
