### ISSUE TITLE
Add Piwik stats

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#493]
We have set up Piwik on the mozfr server, we can activate it for the Transvision subdomain.

That means that we need to add some js in the base template to send hits to Piwik.

For pages without a template (our JSON API calls), I need to investigate if/how those can be counted

We also need to make it an optional setting because we don't want local installs, or non-official installs (on our VPSes or other people's) to send data to our Piwik instance. Similarily, we probably want other installations to send data to a separate Piwik instance or a different profile (for example a separate stats profile for our beta site).

**Comment by pascalchevrel** [comment]
That also means that we will have to apply the patch on the production server before a release so as to make sure that it works and sends data to Piwik correctly

**Comment by flodolo** [comment]
Add a `piwikurl` to config.ini and inject JS only if that's available?

**Comment by pascalchevrel** [comment]
That's the patch I am doing now :)

**Comment by pascalchevrel** [comment]
I couldn't find any way to track non-HTML pages
