### ISSUE TITLE
Beta sites searches broken (fatal error) on prod

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#500]
The beta site is broken on prod, this was caused by https://github.com/mozfr/transvision/commit/701b88abe5df20bd046672bef4623d04bbb46333#diff-4d976c6b5c0ea357b6a48453ca776e91R220

This is not visible locally because this is actually a php bug on keyword case sensibility that was fixed in 5.5 and the server uses 5.4

In 5.4 class keywords were case sensitive which is a bug given that keywords in PHP are not supposed to be case sensitive (https://github.com/php/php-src/blob/PHP-5.5/NEWS#L1686)

Since we are still running 5.4, we need to change the occurrences of 'Self::' by 'self::' (also, generally speaking 'self' is in lowercase.

**Comment by SkySymbol** [comment]
Can I take this one? :-)
