### ISSUE TITLE
Health report is broken for mozilla.org

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#510]
The view falls apart for a locale with only mozilla.org (e.g. 'cak').

For locales with other repositories, it doesn't break because $vcs remains defined from the previous repository (e.g. Gaia), so we display wrong information for last commit.

I tried to add VCS/Git for 'git' repos in ´app/models/health_status.php´ but it fails.
```
[Tue Oct 06 09:15:46.235196 2015] [:error] [pid 83536] [client 192.168.133.50:55408] PHP Notice:  Undefined variable: repository_type in /home/
flodolo/github/transvision/vendor/pascalc/vcs/src/VCS/Git.php on line 16
[Tue Oct 06 09:15:46.235237 2015] [:error] [pid 83536] [client 192.168.133.50:55408] PHP Fatal error:  Cannot access empty property in /home/fl
odolo/github/transvision/vendor/pascalc/vcs/src/VCS/Git.php on line 16
```
I tried to look at the VCS library then, but I don't see easily why it fails (I also expected `repository_type` to be set in the constructor function).

**Comment by pascalchevrel** [comment]
I am going to look at it

**Comment by pascalchevrel** [comment]
ok, found the bug, there is a typo in the VCS library:

**Comment by pascalchevrel** [comment]
ok, found the bug, there is a typo in the VCS library
$this->$repository_type instead of $this->repository_type

I hadn't noticed since I didn't use the library for Git before, only svn and hg.

**Comment by flodolo** [comment]
Good catch, I even looked at the very line...

**Comment by pascalchevrel** [comment]
fixed
