### ISSUE TITLE
Transvision API returns duplicate entires from Translation memory

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#515]
In Pontoon I noticed duplicated Machinery suggestions (mentioned in [Bug 1214719](https://bugzilla.mozilla.org/show_bug.cgi?id=1214719) originally), but seems this is caused by Transvision, as the results are duplicated already in the JSON API response. You can see [here](https://transvision.mozfr.org/api/v1/tm/aurora/en-US/cs/Cancel/?max_results=5&min_quality=70) five identical results for "Cancel", but also the [example link](http://transvision.mozfr.org/api/v1/tm/release/en-US/fr/Home%20page/?max_results=3&min_quality=80) from [JSON-API wiki](https://github.com/mozfr/transvision/wiki/JSON-API) where are two identical results.

**Comment by pascalchevrel** [comment]
Funny that you are reporting this bug because I am working on a change to the API and also noticed it today and I have it fixed in a branch :)

**Comment by pascalchevrel** [comment]
This should be fixed when we fix https://github.com/mozfr/transvision/issues/392 (patch is being reviewed)

**Comment by pascalchevrel** [comment]
Fixed on the beta site:
https://transvision-beta.mozfr.org/api/v1/tm/aurora/en-US/cs/Cancel/?max_results=5&min_quality=70

Will be in Pontoon once we make a new Transvision release (hopefully soon)
