### ISSUE TITLE
Report a bug could add lang tag as a prefix for bug summary

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#529]
Bug summary for bugs filled via Transvision looks like "Translation update proposed for file:entity" and the language is specified by the component. I suggest to add locale tag at the very beginning of the summary, so it will look like "[cs] Translation update proposed for file:entity". When filling new bug, Bugzilla suggests existing entires as a list of bug numbers and summaries, so you see plenty of translation update proposals, but without any specification for what language.

**Comment by pascalchevrel** [comment]
@MikkCZ would you be interested in adding this feature yourself? Seems easy to do and I can mentor you step by step on IRC if you wish :)

**Comment by MikkCZ** [comment]
I had 20 spare minutes in school now, so tried my best to add it quickly. But for some reason PHP 5.4 check failed on something I haven't touched.

**Comment by flodolo** [comment]
I'm rerunning the tests, it's an intermittent failure that we've been fighting for a while.
