### ISSUE TITLE
Commit information in Health status not displaying UTF-8 characters

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#543]
How to reproduce:
- Visit https://transvision.mozfr.org/showrepos/
- Choose "cs" locale
- Choose "Gaia" and "Gaia 2.5"

In the last commit info is shown the last commiters name as `Michal Va???ek` instead of `Michal Vašíček` as [in the repository](https://hg.mozilla.org/releases/gaia-l10n/v2_5/cs/rev/ba9c8ab2741b). Similar situation is for "sk" too, where `Vlado Valaštiak` is written as `Vlado Vala?tiak`.

**Comment by TheoChevalier** [comment]
Interesting, it does not seem related to the font

**Comment by flodolo** [comment]
I think the problem is in the VCS upstream library.
Adding
```
putenv('LANG=en_US.UTF-8');
```
Before exec seems to work for me locally, but I'm not completely sure if that language code is always available :confused:

**Comment by MikkCZ** [comment]
Works now again, not sure, when it has been fixed.
