### ISSUE TITLE
Variables overview false positive for extensions/irc/chrome/chatzilla.properties:pref.bugURL.comment.help

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#544]
I noticed false positive listing for the mentioned string [here](https://transvision.mozfr.org/variables/?locale=cs&repo=aurora). At first, I thought it is listed because of capital S in `%S` etc., but found it in the listing "de" locale too, where capitals are not used.

**Comment by flodolo** [comment]
I don't think it's a false positive, and you should report the error for English.

%s (or %1$s) is different from %S (%1$S), and cuts the output after the first character.

**Comment by flodolo** [comment]
See for example
https://bugzilla.mozilla.org/show_bug.cgi?id=1220376

We definitely want the checks for these variables to be case sensitive.
