### ISSUE TITLE
Add functional tests for all public pages to make sure they exist

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#550]
We should test that all of our public pages do return a 200 value, currently we only test the API but it would be nice to have automatic checks that we don't have a 500 for example on a page we don't use much because we regressed code somewhere.

Setting as easypick.

**Comment by pascalchevrel** [comment]
@SkySymbol interested in taking this one ?

**Comment by SkySymbol** [comment]
Yes :-)

**Comment by flodolo** [comment]
I would also do some basic check, like verifying that a specific element exists. We don't need a DOM representation of the page, searching for things like `<div id='xxxx'>` in the response would be enough for a basic check.

**Comment by SkySymbol** [comment]
Looking for ``<div id="pagecontent">`` is fine?

**Comment by flodolo** [comment]
Personally I would pick a couple of elements specific for each page.

**Comment by pascalchevrel** [comment]
In your patch, please bump the version of Verif in composer.json to 0.4 thanks

**Comment by TheoChevalier** [comment]
Closed via #582
