### ISSUE TITLE
Update Travis file to exclude xdebug + add PHP 5.6 and 7

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#553]
I noticed in the travis log that php-cs-fixer is saying that:
> You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance. 

Looking at the issues on Travis CI repo, this is also causing PHPUnit to be slow, so I guess it also impacts Atoum.

There is documentation to deactivate xdebug there:
https://docs.travis-ci.com/user/languages/php/#PHP-5.6-and-below

We should also replace PHP 5.5 by 5.6 (since we will move to Debian 8 soon) and add 7.0 to the matrix since I hope we will move to that in 2016.

@SkySymbol want to do this one?

**Comment by SkySymbol** [comment]
Yes, you can assign me that issue. Switching to 7.0 will be a huge work :-)

**Comment by pascalchevrel** [comment]
thanks
