### ISSUE TITLE
scandir error in data extraction logs

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#558]
just noticed that in today's logs:
```
PHP Warning:  scandir(/home/pascalc/transvision-data/data/git/mozilla_org/README.md/): failed to open dir: Not a directory in /home/pascalc/transvision/app/classes/Transvision/Dotlang.php on line 24
PHP Warning:  scandir(): (errno 20): Not a directory in /home/pascalc/transvision/app/classes/Transvision/Dotlang.php on line 24
PHP Warning:  Invalid argument supplied for foreach() in /home/pascalc/transvision/app/classes/Transvision/Dotlang.php on line 24
```
Probably caused by the fact that we have a README.md file now on GitHub while we didn't have one on svn and we have code that think that all files in the  repo are folders.

**Comment by flodolo** [comment]
Oh, added it yesterday...

**Comment by pascalchevrel** [comment]
@SkySymbol interested in taking this one ? :)

**Comment by pascalchevrel** [comment]
The error is in the loop of this file:
https://github.com/mozfr/transvision/blob/master/app/scripts/tmx_mozillaorg#L14

We should check that the paths are folders and not files

**Comment by SkySymbol** [comment]
Yes, i'm gonna take this one :-)
