### ISSUE TITLE
Production instance throwing PHP notice of undefined index in gaia view

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#565]
I guess it doesn’t happen locally, but in the apache errors log, I can see many of the following:

[Thu Dec 31 10:43:58 2015] [error] [client 66.249.78.54] PHP Notice:  Undefined index: apps/search/manifest.properties:description in /home/pascalc/transvision/app/views/gaia.php on line 321
[Thu Dec 31 10:43:58 2015] [error] [client 66.249.78.54] PHP Notice:  Undefined index: apps/homescreen/manifest.properties:name in /home/pascalc/transvision/app/views/gaia.php on line 321
[Thu Dec 31 10:43:58 2015] [error] [client 66.249.78.54] PHP Notice:  Undefined index: apps/verticalhome/manifest.properties:name in /home/pascalc/transvision/app/views/gaia.php on line 321
[Thu Dec 31 10:43:58 2015] [error] [client 66.249.78.54] PHP Notice:  Undefined index: shared/branding/unofficial/branding.properties:brandShortName in /home/pascalc/transvision/app/views/gaia.php on line 321
[Thu Dec 31 10:43:58 2015] [error] [client 66.249.78.54] PHP Notice:  Undefined index: shared/branding/unofficial/branding.properties:browserBrandShortName in /home/pascalc/transvision/app/views/gaia.php on line 321
[Thu Dec 31 10:43:58 2015] [error] [client 66.249.78.54] PHP Notice:  Undefined index: shared/branding/unofficial/branding.properties:browserBrandFullName in /home/pascalc/transvision/app/views/gaia.php on line 321

**Comment by flodolo** [comment]
That was fixed in #559
