### ISSUE TITLE
Allow localizers extracting raw translations they’ve pushed during a cycle

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#569]
I’ve been doing that manually for some time now ( Editing https://github.com/mozfr/transvision/blob/master/app/scripts/tmxmaker.py#L54 locally to only return the text, e.g. one string per line, without its ID). Doing so allows me to check all the strings with a grammar checker (mine is http://www.antidote.info/antidote for both French and English). This also works when localizers are using a simple spell checker.

Currently it’s a pain to check 30,000 strings with lots of false positive where I could only check what changed between two branches. I also don’t do it for each release because it’s time consuming. Helping automate this would help catching typos like http://hg.mozilla.org/l10n-central/fr/rev/6cc9480baf4b One could even think of running a Jenkins server with a spell checker.

The data I need are basically the green and orange strings exposed by Elmo on https://l10n.mozilla.org/source/diff/?from=661304c55fbc&to=d9c01cf0f9e9&repo=l10n-central%2Ffr but without string IDs.
In Transvision world that would be New strings + strings displayed in Channel Comparison.
We could expose this in download view if you think several people would be interested in this, or just exposing an API if you don’t want to clutter the UI.

What do you guys think?

**Comment by flodolo** [comment]
I can see a use case for a view displaying the strings changed between two branches, like we do for Gaia, extending https://transvision.mozfr.org/channelcomparison/ with 'Added strings' and 'Removed strings'

On the other hand, I'm not completely sure of how many people would use a file with only these strings, especially in an automated way, given the number of false positives.

**Comment by TheoChevalier** [comment]
A view would be perfect. So maybe we could make the Gaia view generic enough to work for any repo and remove the Channel comparison? + add a way to query any of these set of strings via the API? (Just a thought)

**Comment by flodolo** [comment]
Making the Gaia view more generic would definitely work for me, there are other interesting things in there (e.g. changed English strings).

An API call would work for me.

**Comment by TheoChevalier** [comment]
Definitely agree for English strings, that would be more consistent as currently we have to check https://transvision.mozfr.org/channelcomparison/?locale=en-US&chan1=central&chan2=aurora to have the same data and that’s less obvious.

**Comment by pascalchevrel** [comment]
Talked with Théo today and it seems that improving the channelcomparison view would suffice (basically it only lacks added strings). I would say it's doable during the hackathon.

**Comment by TheoChevalier** [comment]
Follow up, tags still seem to be interpreted:
<img width="1435" alt="capture d ecran 2016-03-14 a 13 54 26" src="https://cloud.githubusercontent.com/assets/1294206/13745376/ff95ffa6-e9ed-11e5-836d-d22eddac0c4a.png">
<img width="1432" alt="capture d ecran 2016-03-14 a 14 06 07" src="https://cloud.githubusercontent.com/assets/1294206/13745377/ffa899ae-e9ed-11e5-8ce2-34889f222d56.png">

From what I can tell, we're missing:
- A way to bulk-select either new strings, modified strings, deleted strings.
- en-US values for new strings
- a simple menu (with anchors, like on the now removed gaia view)
