### ISSUE TITLE
Clean up available URLs

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#583]
While looking at the functional tests for pages, I noticed some strange URLs in the app
* `changelog.php`: I assume it was maintained for retro-compatibility, but I don't think we should keep it (checking access.log on the prod server could confirm that)
* `repocomparizon`, `repocomparison`: empty page
* `channelcomparizon`: we should keep only `channelcomparison`

Also note that most of these views generate warnings in the log.

**Comment by SkySymbol** [comment]
Can you assign me to that issue please?

**Comment by flodolo** [comment]
Done :+1: 

One additional note: besides removing them from the valid urls, we should double check that we're not breaking anything.
