### ISSUE TITLE
In debug mode, send perf metrics in custom http header

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#593]
Currently we can log our metrics in debug mode in the console (or the apache logs if one does not use the php dev server).

I think it would be convenient to also send this data in a custom  http header when in debug mode, this way we can see on the beta server or our VPSs wat the perf of a page is without having to ssh and look at the logs. HTTP headers are also more convenient than outputing directly this infoirmation in the view because the views we need most performance from are the json api and we can't ourput data there.

I quickly checked and it's easy to do, see in the screenshot below the result in firebug, I called the .header Transvision-perf.

![entetes](https://cloud.githubusercontent.com/assets/454375/12425795/c89cc22e-bed6-11e5-8ac0-fbc7b0779c3d.png)

I have something tthat works now but maybe I should let it to a new contributor? Do you like the idea?

**Comment by pascalchevrel** [comment]
We are having an l10n hackathon mid-February and we will have a table with at least 4 people working on Transvision. I am putting that bug in the backlog of bugs to fix for the event.

**Comment by flodolo** [comment]
(side note: the header is visible also in Vanilla devtools: network tab, click on the 200 response, right column)
