### ISSUE TITLE
Transvision is missing pocket.properties

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#599]
For pocket.properties, Transvision has no results. I guess it's because the file is located in [/browser/extensions/pocket/locales/en-US](https://hg.mozilla.org/releases/mozilla-aurora/file/default/browser/extensions/pocket/locales/en-US) versus [/browser/locales/en-US/](https://hg.mozilla.org/releases/mozilla-aurora/file/default/browser/locales/en-US/), where other files are.

**Comment by flodolo** [comment]
Yes, it needs to be added to the tracked folders. See for example https://github.com/mozfr/transvision/pull/527 (which a few more changes, but it's useful to get the idea)

**Comment by pascalchevrel** [comment]
We are having an l10n hackathon mid-February and we will have a table with at least 4 people working on Transvision. I am putting that bug in the backlog of bugs to fix for the event.
