### ISSUE TITLE
Study transliteration possibilities in Transvision

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#600]
A while ago I wrote a script to transliterate from Serbian Cyrillic to Serbian Latin (http://www.chevrel.org/carnet/?post/2013/07/31/Transliterating-Serbian-Cyrillic-to-Serbian-Latin-on-Linux-with-PHP) at that time, Linux distros were not shipping a recent enough ICU library so it had to be compiled manually, but I just tested yesterday and Debian 8 has a recent ICU library which means that the PHP transliteration functions do work correctly.

I think there is some potential for that and we should study if maybe it could be useful for the Serbian views. Examples:
- add a transliteration API and in a Serbian view add a button using it to dynamically transliterate a result string for copy/pasting
- in the download page, add an option for Serbian for transliterated Serbian to allow downloading a TMX in Latin format (I believe all our Serbian localizers use Cyrillic as a basis)
- For the Gaia view, check that what we have in our Latin and Cyrillic repos are actually the same strings by comparing what we have with the transliteration of Cyrillic to Latin.

**Comment by SkySymbol** [comment]
Could you assign me to that issue? thanks

**Comment by pascalchevrel** [comment]
Let's mark it fixed as we have our first stone in the wall, the transliteration API, congrats @SkySymbol ! We'll open specific bugs in the future for other touchpoint of the UI where transliteration could make sense.
