### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/transvision#608]
- Minimum PHP is now 5.6
- Launching tests is now start.sh -tests
- Setting the  remote should use the name "upstream" as it is the general convention for Github forking
- More?

**Comment by SkySymbol** [comment]
I would suggest to link to Francesco's [git tuto](https://flod.org/github/)

**Comment by SkySymbol** [comment]
[Contribution tips](https://github.com/mozfr/transvision#contribution-tips) should be moved from ``README.md`` to ``CONTRIBUTING.md``. And we should link to ``CONTRIBUTING.md`` inside the README In the Contribution tips
