### ISSUE TITLE
multi word searches only searched as exact string, not multiple strings

### ISSUE THREAD

**Issue by Archaeopteryx** [mozfr/transvision#644]
Searches for multiple words only work if they are one exact match. E.g.
The search for 'restart disabled' returns [nothing](https://transvision.mozfr.org/?recherche=restart+disabled&repo=aurora&sourcelocale=en-US&locale=de&search_type=strings) but there are [several strings which contain these words](https://transvision.mozfr.org/?recherche=Restart+with+Add-ons+Disabled&repo=aurora&sourcelocale=en-US&locale=de&search_type=strings).

If I remember correct, this worked in the past (and yielded many uninteresting matches if one had to search for common words).

**Comment by pascalchevrel** [comment]
git bisect gives me this:
87d3405a9c000d3c7255e74c4b477f689e939b36 is the first bad commit
commit 87d3405a9c000d3c7255e74c4b477f689e939b36
Author: Pascal Chevrel <pascal.chevrel@free.fr>
Date:   Sun Nov 15 19:00:48 2015 +0100

    Issues #320: move all our regex logic into a unit tested class

:040000 040000 ecfb0046a95aa33e7791649be2ed55428d390169 31132c9142c3a2ec20238e376b6e18735ef17f2e M	app
:040000 040000 8a401d63d718c7e00d0ef0b880ea133c065cf5a6 786a4f0f94f2527c83181c4a9cfca6a507f5996e M	tests

**Comment by pascalchevrel** [comment]
This is fixed on master and the beta sites yields results:
https://transvision-beta.mozfr.org/?recherche=restart+disabled&repo=aurora&sourcelocale=en-US&locale=de&search_type=strings

Note though that the beta site doesn't get its data updated automatically as production, so you will need to wait for the next release to get that fix on production.

Thanks for reporting the regression.
