### ISSUE TITLE
Gaia view is still using a flawed logic in the consistency section

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#659]
Methods were abstracted, but the logic in Gaia is still flawed. 
https://github.com/mozfr/transvision/blob/master/app/views/gaia.php#L214

* It should first filter, then search for duplicates in English, not the opposite.
* Use the [same logic](https://github.com/mozfr/transvision/blob/master/app/models/consistency.php#L25) used in the consistency view to find duplicates (not intersecting arrays, but iterating over the English duplicates and storing available translations).

The code is slightly different, since here we display all entities.

One possible alternative would be to drop this part of the view entirely and just link at the beginning to the consistency view for the requested repository. It would definitely reduce code duplication.

**Comment by pascalchevrel** [comment]
Given the uncertainties around the future of Gaia, I would just drop Gaia support on this view for the moment.

**Comment by flodolo** [comment]
To clarify: the consistency view is fine, the problem is with the
consistency section in the Gaia view. My suggestion would be to drop that
section and clean up the Gaia view. It would also be an easy pick.
Il 04/mar/2016 09:29, "Pascal Chevrel" <notifications@github.com> ha
scritto:
