### ISSUE TITLE
[consistency] Seemingly similar strings displayed as different

### ISSUE THREAD

**Issue by goofy-bz** [mozfr/transvision#661]
happening sometimes, there is no visible diff between exposed strings.

![diff_unclear 3](https://cloud.githubusercontent.com/assets/858630/13509130/3dad8258-e18a-11e5-8557-64537cac61dd.png)
![diff_unclear 2](https://cloud.githubusercontent.com/assets/858630/13509132/3db37c80-e18a-11e5-9789-51fa86323112.png)
![diff_unclear](https://cloud.githubusercontent.com/assets/858630/13509131/3daf202c-e18a-11e5-87d2-d27fcb0539b0.png)

**Comment by pascalchevrel** [comment]
we should study the differences, it could be errors or it could also be trailing spaces or unicode non-breaking spaces. I am going to have a look

**Comment by flodolo** [comment]
It's a know issue in need of improvement. The strings are similar but different, one of them has one or more trailing whitespaces (you notice them by double clicking).

The idea of keeping (and not trimming) trailing spaces is wanted, but we should highlight them somehow when displaying the string.

**Comment by flodolo** [comment]
The alternative is to trim whitespaces directly when [storing the translation](https://github.com/mozfr/transvision/blob/master/app/models/consistency.php#L49), but I'm afraid we could loose some useful data: why is there a whitespace? Is it needed? It would be useful in general to be able to highlight whitespaces like we do for non breaking spaces in some views.

**Comment by pascalchevrel** [comment]
I can have a look at highlighting whitespaces tomorrow (we actually already do
 on the main view for non breaking spaces in French).

**Comment by pascalchevrel** [comment]
![capture d ecran 2016-03-04 11 08 37](https://cloud.githubusercontent.com/assets/454375/13524132/bb3cb33c-e1f9-11e5-99e1-19c154d67ac7.png)

Here is a screenshot of a patch to expose white space, unicode non breaking spaces and real ellipsis.

**Comment by flodolo** [comment]
Can you show one with a trailing space (e.g. one of the string in goofy's report)?

**Comment by pascalchevrel** [comment]
![capture d ecran 2016-03-04 18 31 40](https://cloud.githubusercontent.com/assets/454375/13534833/5f437956-e237-11e5-8642-af4484337538.png)

**Comment by pascalchevrel** [comment]
all exemples by Googy had a trailing non breaking space, I haven't found one with a real space

**Comment by flodolo** [comment]
I think it looks good.
