### ISSUE TITLE
Highlight of match in results does not work properly

### ISSUE THREAD

**Issue by Joergen** [mozfr/transvision#715]
I noticed that a perfect match in the results isn't highlighted correct.

See https://transvision.mozfr.org/?recherche=+Add+a+Search+Engine&repo= Add a Search Engine aurora&sourcelocale=en-US&locale=da&search_type=strings

Some of the chars in 'Add a Search Engine' is not highlighted.

**Comment by flodolo** [comment]
Fixed [link](https://transvision.mozfr.org/?recherche=Add+a+Search+Engine&repo=aurora&sourcelocale=en-US&locale=da&search_type=strings).

Indeed, the highlighting is off.

**Comment by flodolo** [comment]
The regex approach used to highlight strings is quite dumb. Taking since I'm pretty sure I'm the responsible for that.

**Comment by flodolo** [comment]
[Transvision Beta](https://transvision-beta.mozfr.org/?recherche=Add+a+Search+Engine&repo=aurora&sourcelocale=en-US&locale=da&search_type=strings) (beware that code is up to date on the Beta site, but strings are not. Right now they're about a month old).
