### ISSUE TITLE
Strings are displayed misaligned because of hidden links

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#740]
See for example

![schermata 2016-04-28 alle 11 49 32](https://cloud.githubusercontent.com/assets/3644868/14882117/4dbc632a-0d37-11e6-822f-7403aa97ed7d.png)

**Comment by TheoChevalier** [comment]
Fixed with https://github.com/mozfr/transvision/commit/8243e2bc4bd7a43afa4411bc7b476ba37f3a8f74
