### ISSUE TITLE
This URL shows a blank page

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#741]
This should not show a blank page https://transvision.mozfr.org/string/?entity=toolkit/chrome/global/extensions.properties:csp.error.illegal-host-wildcard&repo=aurora

Works fine with central, shows "Can’t find this string" on beta as expected, but crashes on aurora.

**Comment by flodolo** [comment]
It works just fine on my VM, which is now running Ubuntu 16.04 and php7 (PHP 7.0.4-7ubuntu2)
https://transvision.flod.org/string/?entity=toolkit/chrome/global/extensions.properties:csp.error.illegal-host-wildcard&repo=aurora

Does the log contain any info?

**Comment by TheoChevalier** [comment]
Looks like we’ve got this corruption error once more:

**Comment by TheoChevalier** [comment]
For the record, we got a new one today
1: Got error 'PHP message: PHP Parse error:  syntax error, unexpected 'verkko' (T_STRING), expecting ']' in /srv/mozfr01-data/transvision/TMX/fi/cache_fi_aurora.php on line 8589

**Comment by flodolo** [comment]
OK, can you review this one and merge so it's out of the way?

**Comment by flodolo** [comment]
Ah, didn't found this one when filed the new PR. This will be fixed by #776

**Comment by TheoChevalier** [comment]
Sure, will merge today. I will keep monitor prod until we do a release
