### ISSUE TITLE
Consider reverting the "buttons on hover" change

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#756]
Should we revert the experiment landed in #728 ?
After a few weeks of using it, I find the behavior more misleading than actually improving the UX. For instance, when a single result is displayed on a big screen, the cursor is likely not to be over the result row and it’s not obvious you have to move it over.
This would also fix the layout issue we noticed when string ids are displayed in multiple lines (weird indents)

**Comment by flodolo** [comment]
Personally I agree. I don't think it makes more things more readable, on the other hand it makes some features less discoverable.
