### ISSUE TITLE
Venkman strings still showing up in search

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#770]
The `data/hg/TRUNK_EN-US/venkman` folder needs to be removed manually from server. Then glossaire.sh will take care of removing broken symlinks in the next scheduled run.

**Comment by flodolo** [comment]
Did it on my VPS
https://transvision.flod.org/?recherche=venkman&repo=aurora&sourcelocale=en-US&locale=it&search_type=strings

Compared to
https://transvision.mozfr.org/?recherche=venkman&repo=aurora&sourcelocale=en-US&locale=it&search_type=strings

**Comment by TheoChevalier** [comment]
folder removed, waiting for next glossaire.sh run

**Comment by TheoChevalier** [comment]
Verified fixed ;)
