### ISSUE TITLE
Remove Gaia from supported products

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#778]
It's time to say goodbye to Gaia and clean up after it.

**Comment by TheoChevalier** [comment]
Note for the release: I assume we’ll have to manually rm gaia repositories from the server

**Comment by TheoChevalier** [comment]
Code is removed in #779

**Comment by flodolo** [comment]
Yes, we will need to:
* Manually remove the hg folders GAIA and GAIA_2_5
* Run `./app/scripts/clean_data.py --delete` to remove cache files and unused sources

**Comment by TheoChevalier** [comment]
Note for the release (bis): Remember to revert the mozilla-l10n-query source in travis-config before the release

**Comment by TheoChevalier** [comment]
Note for the release: don’t forget to force TMX in glossaire.sh. (unrelated to gaia, but I’m too lazy to open another release todo list)
