### ISSUE TITLE
Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#796]
From glossaire.sh force-TMX

Extract strings for mozilla.org
PHP Notice:  Undefined index: HTTP_HOST in /srv/mozfr01-data/home/pascalc/transvision/app/inc/constants.php on line 20

Extract strings for Firefox for iOS
PHP Notice:  Undefined index: HTTP_HOST in /srv/mozfr01-data/home/pascalc/transvision/app/inc/constants.php on line 20

**Comment by flodolo** [comment]
Introduced in the very last PR
https://github.com/mozfr/transvision/blob/master/app/inc/constants.php#L20

Should probably define API_ROOT only if `$_SERVER['HTTP_HOST']` is set.
