### ISSUE TITLE
Channel Comparison shows wrong original string

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#800]
See https://transvision.mozfr.org/channelcomparison/?locale=cs&chan1=central&chan2=beta - second row for (toolkit • chrome • global • languageNames.properties or). There should be "Udijština" instead of "Vydavatel certifikátu partnera nebyl rozpoznán.", which is duplicated from the first row (I guess some for cycle issue).

**Comment by TheoChevalier** [comment]
I can reproduce locally with 5.0, can’t with 4.4. It’s likely caused by https://github.com/mozfr/transvision/commit/719d5e91575bd1ea24aa4632ecbbe3e42076b7d3#diff-c84820e1f0f9377a158784c8fae1f3f9R66
Will look at it later, thanks for reporting :)

**Comment by flodolo** [comment]
There's a & before `$value`

Another issue: we should set a min-width on the column to avoid overlapping header and button
![schermata 2016-08-06 alle 12 17 02](https://cloud.githubusercontent.com/assets/3644868/17456199/b9191d70-5bcf-11e6-8f4c-cf675992d953.png)
