### ISSUE TITLE
@@missing@@ shown instead of "Missing string" for string searches

### ISSUE THREAD

**Issue by Archaeopteryx** [mozfr/transvision#802]
https://transvision.mozfr.org/?recherche=use+in+console&repo=aurora&sourcelocale=en-US&locale=de&search_type=strings has two results with "@@missing@@" as German translation. Transvision even run checks against it ("No final dot? Small string?").

**Comment by TheoChevalier** [comment]
Fixed on prod, thanks for reporting :)
