### ISSUE TITLE
Warnings/Notice in logs

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#805]
[Thu Aug 11 03:25:35.062375 2016] [proxy_fcgi:error] [pid 23696:tid 140313620375296] [client 51.255.51.26:45439] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: recherche in /srv/mozfr01-data/home/pascalc/transvision/app/controllers/mainsearch.php on line 29\n'

[Fri Aug 12 01:00:37.878741 2016] [proxy_fcgi:error] [pid 9057:tid 140313719490304] [client 207.46.13.107:2418] AH01071: Got error 'PHP message: PHP Catchable fatal error:  Argument 1 passed to Json\Json::saveFile() must be of the type array, null given, called in /srv/mozfr01-data/home/pascalc/transvision/app/inc/search_counter.php on line 31 and defined in /srv/mozfr01-data/home/pascalc/transvision/vendor/mozillal10n/json/src/Json/Json.php on line 95\n'

Also those errors in unlocalized_all (occurring since we shipped the feature, I’ve never been able to reproduce locally…) https://pastebin.mozilla.org/8891457
This is just a sample, I remember we had to delete 800+MB log files at some point.
It also happen on prod instance. I cleared the cache folder after each release.

We also have those errors, but I assume they are not critical, and probably not due to Transvision code https://pastebin.mozilla.org/8891459

**Comment by flodolo** [comment]
The `search_counter.php` one should be relatively easy to fix: check if we have an array before try to store on file.
https://github.com/mozfr/transvision/blob/master/app/inc/search_counter.php#L31

Same for the first one, add a check on the param before using it, eventually set it to an empty string
https://github.com/mozfr/transvision/blob/master/app/controllers/mainsearch.php#L29

On why it happens? My guess would be that the PHP process dies in the middle of things (see also other logs), which is also the same problem I expect to generate broken TMX files. I've seen error pages before using Transvision, especially on heavy pages like one string view. It should be relatively easy to reproduce, using `&nocache` and making multiple requests to the server.

My VPS doesn't get much traffic, but also doesn't have any trace of this kind of errors.

**Comment by flodolo** [comment]
Should we close this one too? I haven't seen error in a while on my VM, if we exclude the ones from API calls for missing repos.

**Comment by TheoChevalier** [comment]
yup, looked at prod and beta logs yesterday, seen only the errors for unlocalized_all
