### ISSUE TITLE
Remove Pocket support

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#809]
Pocket has moved to GitHub [1], let’s remove the code handling this specific folder.

[1] https://groups.google.com/d/msg/mozilla.dev.l10n/tbi2Rx09y6c/vLPzIpvNBAAJ

**Comment by SkySymbol** [comment]
Hello, can I take this issue please? :-)

**Comment by TheoChevalier** [comment]
Sure :)
