### ISSUE TITLE
Results should be more visible after permorming a search

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#822]
Reported by Julen at the Paris hackathon.

After searching you end up in the results page, but you have to scroll down a bit to get the results. Check google.com for example.

**Comment by TheoChevalier** [comment]
In addition to what will land in #853, once x-channel has landed, I wonder if we can remove the main title “You are looking at the xxx channel”, and reposition the locale code elsewhere. I think the channel info will be less critical, and maybe we can merge it with “Displaying xx results for the string xx in ab-CD:”?

**Comment by flodolo** [comment]
I'll leave this one open. And yes, I think we can remove it.

**Comment by flodolo** [comment]
I think we can close this one.
