### ISSUE TITLE
Change the way we search

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#831]
I confess that I find Transvision search really confusing when it comes to non basic searches.

For example: I want to find all strings containing "set a cookie". I go ahead and search for it, and find something like 29k results! Why? Because we split the sentence in words, and then proceed to search for each unique word in it. And there's "a" in that sentence.

Perfect match doesn't fit, "Whole word" works in a pretty random way and fails at highlighting.

My suggestion would be to:
* Drop the "Whole word" checkbox, and replace it with "Distinct words", or "Search each word": if selected we should replicate the current behavior, searching for each word.
* Default would be to search for the entire sentence, not single words.

I have a WIP branch created just out of curiosity, but wanted to discuss about it before doing any more work and thinking on it.

It's also not a lot of code to change.

**Comment by flodolo** [comment]
Adding more: the API does something completely different. It splits the search terms in words, search for the 1st, then search the results for the 2nd, and so on.
So, only strings containing all words are returned.

**Comment by SkySymbol** [comment]
That makes sense! Usually when you're looking for a sentence you aren't looking for individual words. So +1 on defaulting to 'search the full sentence'

**Comment by TheoChevalier** [comment]
> For example: I want to find all strings containing "set a cookie". I go ahead and search for it, and find something like 29k results! Why? Because we split the sentence in words, and then proceed to search for each unique word in it. And there's "a" in that sentence.

Noticed that a few times as well, but wasn’t sure how we could fix it. I usually work around with Whole word, but yeah, it’s broken behavior.


> My suggestion would be to:
> 
>  -   Drop the "Whole word" checkbox, and replace it with "Distinct words", or "Search each word": if selected we should replicate the current behavior, searching for each word.
> -    Default would be to search for the entire sentence, not single words.
> 
 I think it makes sense

**Comment by flodolo** [comment]
OK, will go ahead and do some more experiments then.

**Comment by flodolo** [comment]
One more thought: is it just me or the API promotion links are reversed?

Example: https://transvision.mozfr.org/?recherche=Set+a+cookie&repo=aurora&sourcelocale=en-US&locale=it&search_type=strings&perfect_match=perfect_match

I expect "en-US" to search in English strings and give me Italian results. Instead, it returns a blank page because it searches in Italian. See for example the search that Pontoon does
https://github.com/mozilla/pontoon/blob/f764d7438156f058cc03aa53ea0150b462a33890/pontoon/base/views.py#L1177

**Comment by flodolo** [comment]
> One more thought: is it just me or the API promotion links are reversed?

Uhm, maybe now I get the logic: "for Italian" -> "with the results in Italian". I think it's really confusing, maybe something like "These results are also available as an API request for **searches in** en-US and it"

**Comment by flodolo** [comment]
Turns out there's a use case for the "Whole words" checkbox, and that's the unlocalized words view.
