### ISSUE TITLE
Next release - Tracking issue

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#834]
### Regenerate TMX after running setup.sh

Note that the fastest way to do it is to run `./glossaire.sh no-update force-tmx no-snapshot`(no point in pulling from repository or updating the data snapshot, it will be done during the next regular update cycle).

### Removing obsolete folders
We can remove `libraries/silme`.

**Comment by TheoChevalier** [comment]
+ Make sure to discard changes in .htaccess before updating

**Comment by TheoChevalier** [comment]
- check that TMX are still working after the release

**Comment by TheoChevalier** [comment]
Done 💯
