### ISSUE TITLE
Make the “l10n” view more obvious

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#839]
UX improvement: make it easier to discover the “l10n” view. 

Here are two ugly ways of doing it:
<img width="432" alt="capture d ecran 2017-01-16 a 16 05 41" src="https://cloud.githubusercontent.com/assets/1294206/21990150/a429ced0-dc05-11e6-8a09-ff472afcfe60.png">

But I’m sure we can do better

**Comment by flodolo** [comment]
Just "all locales" maybe?

**Comment by SkySymbol** [comment]
Maybe change 'link' to 'share'. We can also change the position of the 'l10n' button, to put it next to <source> ?
