### ISSUE TITLE
TMX download broken when trying to download two different products

### ISSUE THREAD

**Issue by flodolo** [mozfr/transvision#841]
I set the TMX download page to en-US, Normal, Central and download the TMX.

If I then set the same option but for mozilla.org, I get the same TMX generated the first time instead of the new one.

I haven't used the download page in a while, not sure when it broke.

**Comment by flodolo** [comment]
It works as expected on my VM
https://transvision.flod.org/downloads/

It's broken on the server, both beta and production.

@TheoChevalier 
Can you try debugging it? One first check would be to verify is the correct file is created or not the 2nd time or if it's some caching problem.

**Comment by TheoChevalier** [comment]
That doesn’t seem right… https://pastebin.mozilla.org/8966020 Aug 4

**Comment by flodolo** [comment]
I would try to create the TMX, check the date and size of the file it generates, then compare after the second request.

**Comment by TheoChevalier** [comment]
Interresting… So it seems the TMX file changes for Spanish when I’m alternatively downloading central then mozilla.org, but not for French, wtf

https://pastebin.mozilla.org/8966041

**Comment by TheoChevalier** [comment]
But at the same time, the downloaded file for Spanish seem to stay the same…

**Comment by flodolo** [comment]
Maybe it's 
https://github.com/mozfr/transvision/blob/master/web/.htaccess

My server is using nginx. I will try locally with Apache and see what happens.

**Comment by flodolo** [comment]
Tested locally with Apache in a VM, everything works as expected.

Something funny in the MozFR server at this point.

**Comment by TheoChevalier** [comment]
@mgoessen Did we add custom Apache rules at some point? I’m runing out of ideas

**Comment by mgoessen** [comment]
hi,

Your intuition was right: the server config was (partially) causing the problem.

As the server set a cache header, the browser use the value in cache and don't really re-download the content if the file have the same name.

I desactivated https://github.com/mozfr/transvision/blob/master/web/.htaccess#L15 and it solve the problem. *You may need to drop part of your local cache*.

I'll let you discuss how you prefer to fix it. Normally even if expire is desactivated Etags should apply.
Maybe however would I recommend you to not reuse the same name for files with different content.

**Comment by TheoChevalier** [comment]
Thanks Geb :)
I guess it’s easy to add a md5 to the file name, using the combination of .php file names used to build the TMX

**Comment by flodolo** [comment]
> I desactivated https://github.com/mozfr/transvision/blob/master/web/.htaccess#L15 and it solve the problem. You may need to drop part of your local cache.

Why is this working fine with a vanilla installation of Apache (on my VM)?

**Comment by mgoessen** [comment]
- theo, sha1 please, however the list of things that have been selected can also do the job. Please think about garbage collecting the files if you use an uniq name. 
- flod: the expire module may not be activated by default, so the rules in .htaccess are ignored. You have to enable it with a2enmod expire; apache2ctl reload. If its missing in the documentation, maybe should it be included :)

**Comment by flodolo** [comment]
> theo, sha1 please, however the list of things that have been selected can also do the job.
I assume he meant take the list of elements build, do the md5 of that list, add it to the filename.

> the expire module may not be activated by default
That was indeed the case, didn't think about checking.

The entire folder is emptied every time we run an update (4 hours).
