### ISSUE TITLE
Layout issue with translated lists

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#850]
Just noticed https://transvision-beta.mozfr.org/string/?entity=mail/chrome/messenger/messengercompose/composeMsgs.properties:mail.compose.attachment_reminder_keywords&repo=aurora

Happens in classic view, too https://transvision-beta.mozfr.org/?sourcelocale=en-US&locale=ru&repo=aurora&search_type=entities&recherche=mail/chrome/messenger/messengercompose/composeMsgs.properties:mail.compose.attachment_reminder_keywords&entire_string=entire_string

I wonder if we can do anything at all, since I’m not sure we want to use word-wrap…

**Comment by flodolo** [comment]
Uh :-\

Maybe it's enough of an edge case to ignore it?

**Comment by TheoChevalier** [comment]
![ignore](https://cloud.githubusercontent.com/assets/1294206/22539422/e7a261d6-e911-11e6-87bd-cc2f5d437775.gif)
