### ISSUE TITLE
Trim search field

### ISSUE THREAD

**Issue by bidaian** [mozfr/transvision#855]
If I type and search for, say, ' viewport' (there is a space before the word), then nothing is found. If I remove it, then the search works.

**Comment by TheoChevalier** [comment]
Thanks for the report :) This is coming from https://github.com/mozfr/transvision/commit/7b548c152ac6fb1e21e62fc96b12da7ba94bfc69
@flodolo, should we put back the trim function on the search term only?

**Comment by flodolo** [comment]
I don't think we should. 

If I search " viewport", I want to search exactly for viewport in the middle of a sentence, or after a punctuation. If I want the word, I search for "viewport". If we trim results, we can only do the latter, besides being really not intuitive.

**Comment by bidaian** [comment]
You're right, you can do both searches like that. I would never even have tried to find viewport in the middle of a sentence by adding a space though. (Now I would :))  I kind of expected full text search with trimmed terms duckduckgo/google/yandex like.

But it's not a big deal. I just copy/pasted and carried over the space character without meaning to, I found nothing and I was suprised. For me that was not intuitive (it took me a bit to figure out). If I had not been completely certain the string was there, I would have stopped there.

By the way, the search suggestions for "<space>viewport" include strings that are not going to be found if trimming does not take place (ImplicitMetaViewportTagFallback). Say I know about the "middle of the sentence search" and type <space>file then in the search suggestions I would probably not want to see the lot of File:, File…, etc. but "Audio Files", "Video Files" ...

Either way, it's an awesome tool. Now that I know about the spaces, if you keep the untrimmed version, I'll simply be careful.

**Comment by flodolo** [comment]
I wonder if it makes sense to put some warning when you search with a leading/trailing whitespace.

As for suggestions, I've indeed kept the old "trim all the things" approach, because that usually finds more results.
