### ISSUE TITLE
Please add Focus for iOS and for Android

### ISSUE THREAD

**Issue by bidaian** [mozfr/transvision#856]
Just a wish. Hope to see them soon!

**Comment by flodolo** [comment]
They are extremely small projects, and the amount of code needed to add new projects doesn't really scale, together with the UI.

I'm not sure if this is going to happen, but open for anyone wanting to look into it.

**Comment by MikkCZ** [comment]
It this is possible to do, there are actually more projects I would like to see. Activity Stream new tab for example, which will be pretty visible part of Firefox, or the Pocket add-on in case Mozilla starts pushing it more in the future.

**Comment by flodolo** [comment]
Focus for iOS should be doable quickly. 

Focus for Android means adding a parser, but the real problem is that adding a new product means touching a lot of places. We need to fix that before trying to add more products.

**Comment by flodolo** [comment]
This is now fixed 🎆
