### ISSUE TITLE
Clicking on Menu button on specific page reloads the same page

### ISSUE THREAD

**Issue by sam1730** [mozfr/transvision#866]
visiting this page

https://transvision.mozfr.org/unchanged/
https://transvision.mozfr.org/productization/

and on click Menu, it reloads the same page, href problem

**Comment by flodolo** [comment]
I can't reproduce this on Firefox. Which browser are you using?

**Comment by sam1730** [comment]
Nightly, Firefox and Chrome

**Comment by sam1730** [comment]
Now this page is fixed
https://transvision.mozfr.org/productization/

but 
https://transvision.mozfr.org/unchanged/

Remains same with the issue

**Comment by flodolo** [comment]
We didn't change anything… Try force reloading the page, maybe you're having some issues with the cache? Note that the menu code is shared across all the pages.

**Comment by sam1730** [comment]
Okays, but if the issues are with the cache then the cache of some pages works fine why only the one page is getting affected.

I tried clearing cache and tried on Internet Explorer too after clearing, for all pages it works fine only on https://transvision.mozfr.org/unchanged/

it remains with the same problem

**Comment by flodolo** [comment]
To clarify, you open https://transvision.mozfr.org/unchanged/, click Menu in the top right corner, and the page reloads? If that's the case, let's see if someone else can reproduce

**Comment by SkySymbol** [comment]
I can reproduce it. I use firefox 52.0.2 on debian sid with user-agent Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0. I will try to identify where is the problem.

**Comment by flodolo** [comment]
Can't reproduce in Firefox 55, 53, Chrome, Safari :-\

**Comment by TheoChevalier** [comment]
Is the page still loading when you click on the menu? I can only reproduce using the Firefox bandwidth throttle feature and clicking on the button very early

**Comment by SkySymbol** [comment]
No, when the bug occurs the page has already been loaded.

**Comment by SkySymbol** [comment]
Weird. On this page I don't have a footer as well.
The bug with the menu is caused by the fact that no javascript is loaded. It seems like everything under [this line](http://localhost:8082/unchanged/) is not loaded.

**Comment by sam1730** [comment]
Please look at the attachment

![capture](https://cloud.githubusercontent.com/assets/8025897/25214228/b27f1c4a-25b3-11e7-9c82-85201e167a9b.JPG)

**Comment by flodolo** [comment]
Uhm, wait. What's the language of your browser?

I supposed you won't have a problem with this (which is the page I see)
https://transvision.mozfr.org/unchanged/?locale=it&repo=central

But you have the problem with en-US
https://transvision.mozfr.org/unchanged/?locale=en-US&repo=central

The problem is that content is not sanitized in this table (it's pretty old), so the page breaks on this `<iframe>`.
https://transvision.mozfr.org/?sourcelocale=en-US&locale=en-US&repo=central&search_type=entities&recherche=editor/ui/chrome/composer/editor.properties:CantEditFramesetMsg&entire_string=entire_string

**Comment by sam1730** [comment]
Yes you are right @flodolo it works fine on
https://transvision.mozfr.org/unchanged/?locale=it&repo=central
