### ISSUE TITLE
Report mozilla.org bugs under Mozilla Localization product

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#879]
I just realized our “Report bug” link for mozilla.org strings files bug under bedrock / L10N, which makes sense in a way, but I’m not sure that’s smart.

Filing them under Mozilla Localization would avoid unnecessary noise in #www, and I don’t think we’re even asking teams in our documentation to track bugs for their locale under Bedrock / L10N, so people might actually miss them unless they look at Elmo (quite unlikely) or the Bug tab in Pontoon.

@flodolo, would that make sense to file them at the same place as for other products?

**Comment by flodolo** [comment]
Bugs show up in webdashboard, since the language is also selected, so they have visibility.

Personally I think that's the right place to report those bugs.

**Comment by TheoChevalier** [comment]
Sounds good
