### ISSUE TITLE
Edit links to pontoon should also show up for mozilla.org and Firefox for iOS

### ISSUE THREAD

**Issue by Pike** [mozfr/transvision#881]
We got a request to have the edit links more widely available.

For beta and release, we might not need to add them now, but it'd be nice to get them for mozilla.org and iOS, too.

Maybe actually revert the logic to not require central, but to exclude beta and release?

**Comment by flodolo** [comment]
At this point I might just look at this from
https://github.com/mozfr/transvision/pull/878/files

**Comment by flodolo** [comment]
Side note: we don't have string IDs in Firefox for iOS and mozilla.org, we can only search for the text in the file.
