### ISSUE TITLE
Add links to Pontoon from the Access Keys report

### ISSUE THREAD

**Issue by bidaian** [mozfr/transvision#883]
The [QA page for checking access keys](https://transvision.mozfr.org/accesskeys/) lists the problems but does not link them back to Transvision or Pontoon, so to fix them you have to manually look for them.

**Comment by flodolo** [comment]
I think it would make sense to include this in a much larger rewrite, which includes using only one piece of code to write results.

Right now they're scattered all over the place, resulting in these differences between views. It also means this would become a quite big change.

**Comment by flodolo** [comment]
This was fixed.
