### ISSUE TITLE
Remove inactive projects from results

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozfr/transvision#894]
I find it distracting to receive matches when searching in English from a project (in my case SeaMonkey) even when it is not translated in my locale.

**Comment by flodolo** [comment]
Sadly it doesn't scale, we read the content of the Mercurial repository. 

If you're not maintaining SeaMonkey, an option is to remove the /suite folder from hg, and track removal in a bug (it can be resurrected at any time).

**Comment by flodolo** [comment]
Thunderbird and Seamonkey are moving to a separate project from Firefox in the coming weeks. This should solve the problem.

**Comment by flodolo** [comment]
This will be fixed by #1021, but we need to wait for
* comm-l10n to be enabled in Pontoon
* get a green light from TB/SM folks to remove the strings from gecko-strings

**Comment by flodolo** [comment]
Just remember about this issue, checking if we can remove the folders now.
