### ISSUE TITLE
Revisit logo font

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/transvision#897]
@flodolo Do you still have the .psd source for the current logo?

We may want to switch to Zilla slab highlighted for `Transvision`

**Comment by flodolo** [comment]
I'm pretty sure I just edited the svg file directly
https://github.com/mozfr/transvision/pull/844

**Comment by TheoChevalier** [comment]
Hm, you’re definitely old-school :) Ok, I will check how much I suck at Photoshop

**Comment by TheoChevalier** [comment]
It looks great here, but I’m worried there would be too much blue with the current bluish background… What do you think about something like that, and without capitalizing Transvision? https://static1.squarespace.com/static/58879499725e2572b9c4e0ec/t/592dfe1eb3db2bf8af733d4a/1496186413997/?format=1500w

**Comment by TheoChevalier** [comment]
But yeah, like this one much, much better! :)
