### ISSUE TITLE
CRITICAL ERROR: no sources available, aborting.

### ISSUE THREAD

**Issue by msoutopico** [mozfr/transvision#898]
Hi there, 

When I run `./start.sh` I get a critical error: 
```

Generate list of locales and supported repositories

Warning: parse_ini_file(/cygdrive/c/Apps/xampp/htdocs/transvision/app/config/config.ini): failed to open stream: No such file or directory in C:\Apps\xampp\htdocs\transvision\app\scripts\generate_sources on line 22

Call Stack:
    0.0010     139512   1. {main}() C:\Apps\xampp\htdocs\transvision\app\scripts\generate_sources:0
    0.0013     139744   2. parse_ini_file() C:\Apps\xampp\htdocs\transvision\app\scripts\generate_sources:22

CRITICAL ERROR: no sources available, aborting.
Check the value for l10nwebservice in your config.ini
```

the value for l10nwebservice in your config.ini is 
`l10nwebservice='https://l10n.mozilla-community.org/mozilla-l10n-query/'`

Do you know what might be wrong?

Cheers, Manuel

**Comment by flodolo** [comment]
Looks like the process is not exactly well documented. Can you try running `app/scripts/dev-setup.sh`?

**Comment by msoutopico** [comment]
Thanks flodolo. I have tried running `app/scripts/dev-setup.sh` but with identical result. Any other tip?

**Comment by flodolo** [comment]
Do you have any error running that script? I'm afraid we might not be compatible with cygwin

**Comment by msoutopico** [comment]
Yes, I get "CRITICAL ERROR: no sources available, aborting.", the same error that I documented in my first message. 

Is there another means to install it under Windows?

**Comment by flodolo** [comment]
I mean the error message when you run `app/scripts/dev-setup.sh`.

**Comment by msoutopico** [comment]
Mmm, not sure I understand what you mean. This is the output I get on the command line:

```
{ transvision }  » ./app/scripts/dev-setup.sh                                       /cygdrive/c/Apps/xampp/htdocs/transvision
Checking if Transvision sources are available...
Generate list of locales and supported repositories

Warning: parse_ini_file(/config.ini): failed to open stream: No such file or directory in C:\Apps\xampp\htdocs\transvision\app\scripts\generate_sources on line 21

Call Stack:
    0.0015     139512   1. {main}() C:\Apps\xampp\htdocs\transvision\app\scripts\generate_sources:0
    0.0021     139696   2. parse_ini_file() C:\Apps\xampp\htdocs\transvision\app\scripts\generate_sources:21

CRITICAL ERROR: no sources available, aborting.
Check the value for l10nwebservice in your config.ini
```

Is this what you're asking for? 

Thanks.

**Comment by flodolo** [comment]
> Is this what you're asking for?

Yes. Unfortunately, it doesn't even find the config file to parse
https://github.com/mozfr/transvision/blob/4250ee94ab6aef48073b92eab3b83dd23b30fcb6/app/scripts/generate_sources#L21

And there are a ton of places that depend on parsing that file, not just generate_sources. It looks like Transvision is not going to work with your system, the easiest way is to install a VM with Linux.

**Comment by flodolo** [comment]
Thanks. We definitely need to update our README :-\
