### ISSUE TITLE
ERROR: The 'install' variable in your config.ini file is probably wrong

### ISSUE THREAD

**Issue by msoutopico** [mozfr/transvision#899]
Good morning. 

I have followed the instructions to run the snapshot installation of transvision in a VM running ubuntu. This is the output I get:

```
souto@sondou9:/var/www/html/transvision$ sudo ./start.sh 
WARNING: There is no app/config/config.ini file. Creating one based based on app/config/config.ini-dev template.
Checking if Transvision sources are available...
Generate list of locales and supported repositories
* Saving list of locales for release
* Saving list of locales for beta
* Saving list of locales for central
* Saving list of locales for firefox_ios
* Saving list of locales for mozilla_org
* Saving JSON record of all supported repositories
* Saving JSON record of tools and their supported locales
ERROR: The 'install' variable in your config.ini file is probably wrong as there is no git repository at the location you provided.
Launching PHP development server (php -S localhost:8082 -t web/ app/inc/router.php)
PHP 7.0.22-0ubuntu0.16.04.1 Development Server started at Wed Oct 11 10:53:42 2017
Listening on http://localhost:8082
Document root is /var/www/html/transvision/web
Press Ctrl-C to quit.
```

In a nutshell, it seems to do the trick and it launches the server, however there's an error, and I see nothing in the `http://localhost:8082` page in my browser. 

Any tips what is wrong? Thanks! 
Manuel

**Comment by flodolo** [comment]
Sorry you're going through all these issues, it looks like nobody tried the snapshot method in a while.
Hopefully @TheoChevalier or I will be able to test it.

**Comment by flodolo** [comment]
Did you get any error related to installing composer dependencies? 

Try removing the line about phpdocumentor from composer.json (we're fixing it in a pending PR), and run start.sh again

It seems to be working fine here.

**Comment by msoutopico** [comment]
Thanks. I have installed `git` and I have cloned the package again and I'm running the `start.sh` script again from my home, now it seems to be downloading "a snapshot of data from Transvision Web site"...

**Comment by msoutopico** [comment]
It didn't work. I have tried following your hint above (removing that line in composer.json) but to no avail. Now I get the following error when I try to open `http://localhost:8082`: 

```
[Wed Oct 11 12:30:40 2017] PHP Fatal error:  Uncaught Error: Call to undefined function Transvision\mb_internal_encoding() in /home/souto/transvision/app/inc/init.php:9
Stack trace:
#0 /home/souto/transvision/app/inc/router.php(60): require_once()
#1 {main}
  thrown in /home/souto/transvision/app/inc/init.php on line 9
```
Thanks.

**Comment by flodolo** [comment]
Check the dependencies. You're missing php-mbstring
https://github.com/mozfr/transvision#dependencies

**Comment by flodolo** [comment]
Check the dependencies. You're missing php-mbstring
https://github.com/mozfr/transvision#dependencies

See https://askubuntu.com/questions/491629/how-to-install-php-mbstring-extension-in-ubuntu

**Comment by flodolo** [comment]
One more note: we're in the middle of a huge change, so the code will expect data that is not in production for a few more days.

**Comment by flodolo** [comment]
Changes landed in production. You'll need to remove the folder in web/TMX, and run start.sh again.

I assume we can close this issue though?

**Comment by flodolo** [comment]
I'm going to close this, let me know if you need any help
