### ISSUE TITLE
500 error when there are too many results in the entities view

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#901]
Entities search result view is missing 200 results truncation, which leads to long load time or 500 errors in the worst case:
- [accesskey](https://transvision.mozfr.org/?recherche=accesskey&repo=gecko_strings&sourcelocale=en-US&locale=cs&search_type=entities) (long load time)
- [label](https://transvision.mozfr.org/?recherche=label&repo=gecko_strings&sourcelocale=en-US&locale=cs&search_type=entities) (result 500 error)

**Comment by flodolo** [comment]
I'm working on this. Also realized that we broke the JS updating the number of the results at some point.
