### ISSUE TITLE
False positive accesskey error

### ISSUE THREAD

**Issue by MikkCZ** [mozfr/transvision#910]
For Czech there is a false positive accesskey error for `decoder.noCodecs.accesskey` (see https://transvision.mozfr.org/accesskeys/?locale=cs&repo=gecko_strings). But it should belong to `decoder.noCodecs.button` instead of `decoder.noCodecs.message`. I am not sure, how exactly the detection works, but can you prefer `.button` before `.message` suffix?

**Comment by flodolo** [comment]
The logic is that we strip .accesskey (e.g. getting `decode.noCodecs`), the try one of 

```
$ak_labels = ['.label', '.title', '.message', ''];
```

At the moment we don't even look for `.button`. I wonder if adding this as an [exception](https://github.com/mozfr/transvision/blob/master/app/models/accesskeys.php#L44) would be better than trying to fit it into the logic.
