### ISSUE TITLE
Adding "All" option for searching across repositories

### ISSUE THREAD

**Issue by facyber** [mozfr/transvision#925]
I use a lot transvision and there are many times when I need to compare Desktop and Android strings versions so they could be localized in the same way. It would be nice to have option to search across all repositories at once, not just one as it is now. This would shorter time spent on constant changing between the products, especially as there are now Focus for both iOS and Android, pluse Firefox Android and Desktop and mozilla.org. I believe many localizations are trying to optimize their translations for the all platforms to be similar as possible.

**Comment by flodolo** [comment]
I believe the back-end (getting the strings) would be trivial: add a *fake* product to the list, retrieve strings for all known repository.

On the other hand, I don't think the front-end can be done without a full rewrite that cleans up the current mess and code duplication in views.

**Comment by flodolo** [comment]
This is fixed in #1021. It should be deployed to production this week, we need to wait for the comm-l10n change to be set up in Pontoon.
