### ISSUE TITLE
Search string containing ampersand is truncated just before it

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozfr/transvision#929]
STR:
Search for the string "$BrandShortName &Safe Mode" and observe the results.

Expected
The search field has the same content as before page reload and the search results contain the whole string.

Observed
The string in the search field is truncated before the ampersand character and the search results are missing the "Safe Mode" part of the query.

Workaround
Use the checkbox "Every word".

**Comment by StoyanDimitrov** [comment]
Additionally there is a problem with html special characters in the links form consistency view. So far I have observations for the "&" breaking the links. If needed will file a separate issue.

**Comment by flodolo** [comment]
I can't seem to reproduce any of this, so I wonder if I'm misunderstanding the issue.

> Search for the string "$BrandShortName &Safe Mode" and observe the results.

I tried and I get the [expected results](https://transvision.mozfr.org/?recherche=%24BrandShortName+%26Safe+Mode&repo=gecko_strings&sourcelocale=en-US&locale=bg&search_type=strings).

![schermata 2017-12-18 alle 08 21 38](https://user-images.githubusercontent.com/3644868/34094204-7d30ec4e-e3cc-11e7-8506-fb0aa4f71df9.png)


> Additionally there is a problem with html special characters in the links form consistency view. So far I have observations for the "&" breaking the links. If needed will file a separate issue.

For example, in the [bg page](https://transvision.mozfr.org/consistency/?locale=bg&repo=gecko_strings&filter=all), I click on `&brandShortName; Safe Mode` and get to [this link](https://transvision.mozfr.org/?sourcelocale=en-US&locale=bg&repo=gecko_strings&search_type=strings&recherche=%26brandShortName%3B+Safe+Mode&entire_string=entire_string), which seems fine.

**Comment by StoyanDimitrov** [comment]
It turns out it was an add-on messing with it.

**Comment by flodolo** [comment]
Can you tell which one for posterity's sake? ;-)
