### ISSUE TITLE
entity firstdayofweek.default known but not its value for en-US

### ISSUE THREAD

**Issue by Archaeopteryx** [mozfr/transvision#940]
https://transvision.mozfr.org/?recherche=firstdayofweek.default&repo=gecko_strings&sourcelocale=en-US&locale=fr&search_type=entities lists
mail • chrome • messenger • datetimepicker.dtd
firstdayofweek.default 
with these values:
en-US: Warning: Source string is empty
fr: 1

https://dxr.mozilla.org/comm-central/search?q=firstdayofweek.default says it's set to 0.

**Comment by flodolo** [comment]
Ugh, thanks for reporting. We had a similar silly bug for translations, I bet it's the same problem for source.
