### ISSUE TITLE
Access Key check looks at <entity>.message instead of <entity>.button

### ISSUE THREAD

**Issue by TonnesM** [mozfr/transvision#949]
When using the access keys check on Transvision for my locale (nl), I noticed decoder.decodeError.**accesskey** apparently looks at decoder.decodeWarning.**message** instead of decoder.decodeError.**button**, resulting in an incorrect entry.

I understand this needs to be added as an exception?

**Comment by flodolo** [comment]
I'll wait a few more days to push to prod, in case something else comes up.
