### ISSUE TITLE
Edit in Pontoon does not work if the string is not translated in id-less projects

### ISSUE THREAD

**Issue by bidaian** [mozfr/transvision#951]
[This](https://transvision.mozfr.org/?recherche=windows+xp&repo=mozilla_org&sourcelocale=en-US&locale=zam&search_type=strings) is an example search. The translation says "Warning: Empty string" and the [Edit in Pontoon](https://pontoon.mozilla.org/zam/mozillaorg/download_button.lang/?string=7865) link points to the right file, but not the right string, because the search parameter is empty and the string number is not right either.

**Comment by flodolo** [comment]
It doesn't happen in all projects, only in those where we need to generate an ID: in those cases we need to search for the translation. 

I guess we could add yet another fall back (search for the English string if the translation is empty), not sure if it's worth though, since it's a minor case, and we still reach the right file.

**Comment by flodolo** [comment]
Interesting. We already have a [check](https://github.com/mozfr/transvision/blob/master/app/classes/Transvision/ShowResults.php#L274) to not display the link on free text repos, when the translation is missing. But it fails for mozilla.org

**Comment by bidaian** [comment]
I guess it would be better to have a half-working link than none at all. Though the search for the English string would be the best.

**Comment by flodolo** [comment]
> I guess it would be better to have a half-working link than none at all. Though the search for the English string would be the best.

I don't believe it's the goal of Transvision to let you access a missing string, that's Pontoon's. The edit link is there if you notice issues and want to fix them.

**Comment by bidaian** [comment]
> I don't believe it's the goal of Transvision to let you access a missing string, that's Pontoon's. The edit link is there if you notice issues and want to fix them.

I kind of considered a missing string an issue when I did the search. And having found it through Transvision (I love it, it is **so** helpful) I wanted to fix it from there. But I do get your point. Fair enough, it's not Transvision's goal, so removing the link might be the right way to solve it.

**Comment by flodolo** [comment]
Fixed via https://github.com/mozfr/transvision/pull/953 (still not in production)
