### ISSUE TITLE
Bug in entity: useless self-assignment

### ISSUE THREAD

**Issue by ArturLisowski** [mozfr/transvision#959]
app/models/api/entity.php
unusefull line:
$strings[$entity] = $strings[$entity];

**Comment by flodolo** [comment]
Thanks, makes more sense now. As explained there, it comes out of a larger change that removed `trim()` across the project.

Out of curiosity, did you find it when looking at code or just running some tool?

**Comment by ArturLisowski** [comment]
> Thanks, makes more sense now. As explained there, it comes out of a larger change that removed `trim()` across the project.
> 
> Out of curiosity, did you find it when looking at code or just running some tool?

I found it when looking at code.
